name: Deploy to Server (Local ARM64 Build)

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout репозитория
        uses: actions/checkout@v4

      - name: 🚀 SSH: Pull + Build + Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/mp-price-bot
            git pull origin master
            docker compose down
            docker compose up -d --build
